# Generated by Django 2.2.6 on 2019-10-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField(max_length=200, null=True)),
                ('level', models.IntegerField(max_length=200, null=True)),
                ('question', models.TextField()),
                ('ch_1', models.TextField()),
                ('ch_2', models.TextField()),
                ('ch_3', models.TextField()),
                ('ch_4', models.TextField()),
                ('answer', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField(max_length=200, null=True)),
                ('level', models.IntegerField(max_length=200, null=True)),
                ('question', models.TextField()),
                ('ch_1', models.TextField()),
                ('ch_2', models.TextField()),
                ('ch_3', models.TextField()),
                ('ch_4', models.TextField()),
                ('answer', models.CharField(max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
