# Generated by Django 2.2.6 on 2019-10-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191013_0543'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='math',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
