# Generated by Django 2.2.6 on 2019-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191019_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
