# Generated by Django 2.2.6 on 2019-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20191019_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='test_id',
        ),
        migrations.AddField(
            model_name='math',
            name='_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='_id',
            field=models.CharField(default=3, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
