# Generated by Django 2.2.6 on 2019-10-20 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_auto_20191019_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=6)),
                ('stat_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatQuizAnswersAsStat', to='quiz.Stat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatQuizAnswersAsUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MathQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=6)),
                ('mat_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MathQuizAnswersAsMath', to='quiz.Math')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MathQuizAnswersAsUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
